"""Per-niche prompt + seed config. Add a niche by adding an entry."""
from __future__ import annotations

NICHES = {
    "sleep": {
        "site_slug": "sleepupgradehub",
        "domain": "sleepupgradehub.com",
        "categories": [
            "Sleep Trackers", "Sleep Tools", "Habits", "Supplements",
            "White Noise", "Sleep Environment",
        ],
        "pillar_posts": [
            ("/sleep-habits-and-routines-that-work", "Sleep Habits & Routines"),
            ("/optimize-bedroom-environment-for-better-sleep", "Bedroom Optimization"),
            ("/best-sleep-supplements-guide", "Sleep Supplements Guide"),
            ("/best-sleep-tools-and-gadgets-review", "Sleep Tools Review"),
            ("/best-sleep-trackers-comparison-guide", "Sleep Trackers Comparison"),
            ("/best-white-noise-machines-for-sleep", "White Noise Machines"),
        ],
        "seed_keywords": [
            "best sleep tracker", "best sleep mask", "best white noise machine",
            "best magnesium for sleep", "best mattress", "best pillow",
            "best weighted blanket", "best sleep supplement", "best cooling mattress",
            "best sunrise alarm", "how to fall asleep", "how to sleep better",
            "how to fix sleep schedule", "why cant i sleep", "why do i wake up",
            "how to get more deep sleep", "oura vs whoop", "oura vs apple watch",
            "eight sleep vs chilipad", "melatonin vs magnesium",
            "oura ring review", "whoop review", "eight sleep review",
            "sleep cycles explained", "rem sleep", "deep sleep",
            "sleep hygiene", "circadian rhythm",
        ],
        "modifiers": ["", "2025", "reddit", "for adults", "for side sleepers",
                      "for anxiety", "natural", "how to use", "what is",
                      "why does", "how long", "side effects of"],
        "subreddits": ["sleep", "biohackers", "insomnia"],
        "image_query_template": "{keyword} bedroom sleep",
        "image_fallback_queries": ["bedroom interior", "peaceful sleep", "minimalist bedroom"],
        "voice": "Expert sleep writer. Conversational tone. Real 2025 prices. Short paragraphs. Cite Reddit when used.",
    },

    "trading": {
        "site_slug": "tradinghub",
        "domain": "tradinghub.com",
        "categories": ["Prop Firms", "Forex Brokers", "Strategies", "Tools", "Education", "Crypto"],
        "pillar_posts": [],
        "seed_keywords": [
            "best prop firm 2025", "best forex broker", "ftmo review", "myforexfunds review",
            "topstep review", "best forex strategy", "supply demand trading",
            "smart money concepts", "ict trading", "best trading platform",
            "tradingview vs metatrader", "best forex pairs", "scalping vs swing trading",
            "best risk management", "trading psychology", "forex vs crypto",
            "best prop firm for beginners", "passing prop firm challenge",
            "what is forex", "how to start day trading", "what is a pip in forex",
            "how to read candlestick patterns", "what is leverage in trading",
            "how much money to start trading", "what is a prop firm",
            "how to backtest a strategy", "what is slippage", "how to journal trades",
        ],
        "modifiers": ["", "2025", "reddit", "review", "for beginners",
                      "explained", "step by step", "vs", "tutorial"],
        "subreddits": ["Forex", "Daytrading", "propfirm"],
        "image_query_template": "{keyword} trading desk",
        "image_fallback_queries": ["trading screens", "stock chart", "forex charts"],
        "voice": "Trading expert. No hype. Risk-aware. Real numbers. Distinguish demo vs live performance.",
    },

    "ai-tools": {
        "site_slug": "aitoolsedge",
        "domain": "aitoolsedge.com",
        "categories": ["Coding AI", "Writing AI", "Image AI", "Productivity", "Comparisons", "How-To"],
        "pillar_posts": [],
        "seed_keywords": [
            "best ai coding assistant", "claude vs chatgpt", "cursor vs windsurf",
            "best ai for writing", "best ai image generator", "midjourney vs dall-e",
            "best ai for spreadsheets", "ai tools for developers", "ai tools for marketers",
            "best free ai tools", "ai agents 2025", "best llm api",
            "anthropic api guide", "openai api guide", "best ai chatbot",
            "perplexity vs chatgpt", "claude opus review", "gpt-5 review",
            "how to use chatgpt", "what is claude api", "how to write a system prompt",
            "what is rag", "how to fine tune a model", "what is a token in ai",
            "how to use cursor", "what is mcp", "how does prompt caching work",
            "why is my ai hallucinating", "how to choose an llm",
        ],
        "modifiers": ["", "2025", "review", "vs", "alternatives", "free",
                      "tutorial", "explained", "for beginners"],
        "subreddits": ["LocalLLaMA", "ArtificialIntelligence", "ChatGPT"],
        "image_query_template": "{keyword} laptop technology",
        "image_fallback_queries": ["modern laptop", "tech workspace", "futuristic technology"],
        "voice": "Hands-on AI reviewer. Specific use cases. Cost per task. Honest about limits.",
    },

    "dev-tools": {
        "site_slug": "codestackhub",
        "domain": "codestackhub.com",
        "categories": ["IDEs", "Frameworks", "DevOps", "Databases", "Cloud", "Tutorials"],
        "pillar_posts": [],
        "seed_keywords": [
            "best ide 2025", "vscode vs cursor", "next.js vs remix", "astro vs next.js",
            "best react framework", "best python ide", "vercel vs netlify",
            "supabase vs firebase", "best postgres host", "turso vs neon",
            "best monorepo tool", "best ci cd tool", "github actions tutorial",
            "best api framework", "best orm", "drizzle vs prisma",
            "tailwind vs vanilla css", "shadcn ui review",
            "what is server actions", "how to deploy next.js to vercel",
            "what is an orm", "how to use docker", "what is kubernetes",
            "how does typescript work", "what is server side rendering",
            "how to use github copilot", "what is a monorepo",
            "why is my build slow", "how to optimize lighthouse score",
        ],
        "modifiers": ["", "2025", "review", "vs", "tutorial", "explained", "for beginners"],
        "subreddits": ["webdev", "programming", "nextjs", "reactjs"],
        "image_query_template": "{keyword} coding screen",
        "image_fallback_queries": ["code editor", "developer desk", "programming"],
        "voice": "Senior engineer. Production-grade tradeoffs. Show actual code patterns. No marketing fluff.",
    },
}
